-- • GIVEN THE CUSTOMER RELATION BELOW.
-- CID NAME ADDRESS CITY POSTALCODE COUNTRY

-- 1 Alfreds Futterkiste 57 Obere Street Berlin 12209 Germany

-- 2 Ana Trujillo 3 Beach Street Miami 25021 Florida

-- CUSTOMER(CID, NAME, ADDRESS, CITY,
-- POSTALCODE, COUNTRY)

-- WRITE A SQL STATEMENT TO SELECT THE CUSTOMER ID, CITY
-- AND COUNTRY FROM CUSTOMER WHERE COUNTRY IS
-- "Germany" AND CITY MUST BE "Berlin" OR "Munchen".

-- ACTIVITY 1
SELECT
    CID,
    CITY,
    COUNTRY
FROM
    CUSTOMER
WHERE
    COUNTRY = 'Germany'
    AND (CITY = 'Berlin'
    OR CITY = 'Munchen');

-- • GIVEN THE CUSTOMER RELATION BELOW.
-- CUSTOMER(CID, NAME, ADDRESS, CITY,
-- POSTALCODE, COUNTRY)

-- List the number of customers in each country. Only

-- INCLUDE COUNTRIES WITH MORE THAN 5 CUSTOMERS. SORT THE
-- RESULTS IN DESCENDING ORDER BASED ON COUNTRY.

-- ACTIVITY 2
SELECT
    COUNTRY,
    COUNT(CID)
FROM
    CUSTOMER
GROUP BY
    COUNTRY
HAVING
    COUNT(DISTINCT CID) > 5
ORDER BY
    COUNTRY DESC;

-- WRITE A SQL TO DISPLAY ALL PAST JOBS DONE BY
-- ANY OF THE EMPLOYEES WHO IS PRESENTLY EARNING

-- a salary on and above 12000.

-- • SHOW EMPLOYEE ID, JOB START DATE, JOB END DATE AND JOB ID.
-- EMPLOYEE(EMP_ID, FIRST_NAME, LAST_NAME,
-- EMAIL, SALARY, COMMISSION)

-- JOB_HISTORY(EMP_ID, START_DATE, END_DATE,
-- JOB_ID)

--  ACTIVITY 4
SELECT
    E.EMP_ID,
    JH.START_DATE,
    JH.END_DATE,
    JH.JOB_ID
FROM
    EMPLOYEE    E
    INNER JOIN JOB_HISTORY JH
    USING (EMP_ID)
WHERE
    E.SALARY >= 12000;