/************************************************************************************/
/* This SQL script creates the following tables needed to do Tutorial 03   */
/************************************************************************************/

CREATE TABLE INDUSTRY (
	INDID CHAR(2),
	INDDESC VARCHAR(60),
	CONSTRAINT INDIDFK PRIMARY KEY (INDID)
);

CREATE TABLE STOCKCOMPANY (
	SCPTICKERSYMBOL VARCHAR(4),
	SCPNAME VARCHAR(50),
	SCPSHORTNAME VARCHAR(15),
	SCPADDR1 VARCHAR(25),
	SCPADDR2 VARCHAR(25),
	SCPCITY VARCHAR(25),
	SCPSTATE CHAR(2),
	SCPCOUNTRYNAME VARCHAR(50),
	SCPPOSTALCODE VARCHAR(11),
	SCPINDUSTRYID CHAR(2),
	SCPCHANGEDATE DATE DEFAULT SYSDATE NOT NULL,
	SCPCHANGEBY VARCHAR(30) DEFAULT USER NOT NULL,
	CONSTRAINT SCPTICKERSYMBOLPK PRIMARY KEY (SCPTICKERSYMBOL),
	CONSTRAINT SCPINDUSTRYIDFK FOREIGN KEY (SCPINDUSTRYID) REFERENCES INDUSTRY (INDID)
);

CREATE TABLE STOCKYEND (
	STOCKYENDTICKERSYMBOL VARCHAR(4)
);

CREATE TABLE STOCKCLOSING (
	SCTICKERSYMBOL VARCHAR(4),
	SCCLOSINGDATE DATE,
	SCOPENPRICE NUMBER(9, 2),
	SCHIGHPRICE NUMBER(9, 2),
	SCLOWPRICE NUMBER(9, 2),
	SCCLOSEPRICE NUMBER(9, 2),
	SCVOLUME NUMBER(13),
	SCADJUSTEDPRICE NUMBER(9, 2),
	CONSTRAINT SCTICKERSYMBOLPK PRIMARY KEY (SCTICKERSYMBOL, SCCLOSINGDATE),
	CONSTRAINT SCTICKERSYMBOLFK FOREIGN KEY (SCTICKERSYMBOL) REFERENCES STOCKCOMPANY (SCPTICKERSYMBOL)
);

/************************************************************************************/
/* End of create tables                                                             */
/************************************************************************************/